[workspace]
[package]
version = "0.1.0"
name = "chess-script"
edition = "2021"

[dependencies]
sphinx-sdk = { path = "../../../sdk" }

[build-dependencies]
sphinx-helper = { path = "../../../helper" }
