[workspace]
[package]
version = "0.1.0"
name = "fibonacci-benchmark-program"
edition = "2021"

[dependencies]
wp1-zkvm = { path = "../../../zkvm/entrypoint" }

[build-dependencies]
wp1-helper = { path = "../../../helper" }
