[package]
name = "wp1-precompiles"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
bincode = "1.3.3"
cfg-if = "1.0.0"
getrandom = { version = "0.2.12", features = ["custom"] }
k256 = { version = "0.13.3", features = ["ecdsa", "std", "bits"] }
serde = { version = "1.0.196", features = ["derive"] }
hybrid-array = "0.2.0-rc"