[book]
authors = ["WP1 and SP1 Contributors"]
language = "en"
multilingual = false
src = "book"
title = "WP1 Book"
description = "A book on all things Reth"

[output.html]
theme = "book/theme"
git-repository-url = "ssh://git@github.com/lurk-lab/sphinx"
default-theme = "ayu"
no-section-label = true

[output.html.fold]
enable = true
level = 1

[output.html.playground]
runnable = false

[build]
build-dir = "target/book"

[preprocessor.template]
before = ["links"]

[preprocessor.index]

[preprocessor.links]