[workspace]
[package]
version = "0.1.0"
name = "ssz-withdrawals-script"
edition = "2021"

[dependencies]
wp1-sdk = { path = "../../../sdk" }

[build-dependencies]
wp1-helper = { path = "../../../helper" }
