[workspace]
[package]
name = "bls12381-pairing"
version = "0.1.0"
edition = "2021"

[dependencies]
sphinx-zkvm = { path = "../../../zkvm/entrypoint" }

bls12_381 = { git = "https://github.com/lurk-lab/bls12_381", branch = "zkvm" }
