[workspace]
[package]
version = "0.1.0"
name = "tendermint-script"
edition = "2021"

[dependencies]
sphinx-core = { path = "../../../core", features = ["neon"] }
sphinx-sdk = { path = "../../../sdk" }
reqwest = { version = "0.11", features = ["json", "default-tls"] }
tokio = { version = "1", features = ["full"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
serde = { version = "1.0", default-features = false, features = ["derive"] }
tendermint = { version = "0.34.0", default-features = false }
tendermint-light-client-verifier = { version = "0.34.0", default-features = false, features = [
  "rust-crypto",
] }
bincode = "1.3.3"
itertools = "0.12.1"
serde_cbor = "0.11.2"
sha2 = "0.10.8"

[build-dependencies]
sphinx-helper = { path = "../../../helper" }
