[workspace]
[package]
version = "0.1.0"
name = "json-script"
edition = "2021"

[dependencies]
serde = "1.0.197"
serde_json = "1.0.114"
sphinx-sdk = { path = "../../../sdk" }
lib = { path = "../lib" }

[build-dependencies]
sphinx-helper = { path = "../../../helper" }
