[workspace]
[package]
version = "0.1.0"
name = "cycle-tracking-program"
edition = "2021"

[dependencies]
sphinx-zkvm = { path = "../../../zkvm/entrypoint" }
sphinx-lib = { path = "../../../zkvm/lib" }
sphinx-derive = { path = "../../../derive" }
