name: Docker Gnark

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - "**"
    paths:
      - "recursion/gnark-ffi/**"
      - "recursion/gnark-cli/**"
      - "!recursion/gnark-ffi/assets/**"
  merge_group:

jobs:
  test-docker:
    name: Test
    runs-on: runs-on,runner=64cpu-linux-arm64
    env:
      CARGO_NET_GIT_FETCH_WITH_CLI: "true"
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup CI
        uses: ./.github/actions/setup

      - name: Build docker image
        run: |
          docker build -t sp1-gnark -f ./Dockerfile.gnark-ffi .

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        env:
          SP1_GNARK_IMAGE: sp1-gnark
        with:
          command: test
          toolchain: nightly-2024-04-17
          args: --release -p sp1-prover -- --exact tests::test_e2e
