name: Gnark Tests

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  groth16:
    name: Groth16
    runs-on: warp-ubuntu-latest-arm64-8x
    env:
      CARGO_NET_GIT_FETCH_WITH_CLI: "true"
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Setup CI
        uses: ./.github/actions/setup
        with:
          pull_token: ${{ secrets.PULL_TOKEN }}

      - name: Install sp1 toolchain
        run: |
          curl -L https://sp1.succinct.xyz | bash
          echo "/root/.sp1/bin" >> $GITHUB_PATH
          /root/.sp1/bin/sp1up

      - name: Run make groth16
        run: make groth16
        working-directory: prover
        env:
          RUSTFLAGS: -Copt-level=3 -Cdebug-assertions -Coverflow-checks=y -Cdebuginfo=0 -Ctarget-cpu=native
          RUST_LOG: "info"
          RUST_BACKTRACE: "1"
          FRI_QUERIES: "1"
          SP1_DEV_WRAPPER: "false"
